### ISSUE TITLE
Shelly Plus1PM support ?

### ISSUE THREAD

**Issue by TheGrumpyBadger** [Telekatz/venus.dbus-shellyPlug#1]
I can get data from all my ShellyPlugs, thank you.
What is not working is getting data from the Plus1PM.

https://shelly-api-docs.shelly.cloud/gen2/Devices/ShellyPlus1PM

Result of

http://[192.168.178.202/rpc/Shelly.GetStatus](http://192.168.178.202/rpc/Shelly.GetStatus)

is:

{"ble":{},"cloud":{"connected":true},"input:0":{"id":0,"state":false},"mqtt":{"connected":false},"switch:0":{"id":0, "source":"init", "output":true, "apower":28.2, "voltage":224.4, "current":0.256, "aenergy":{"total":66102.508,"by_minute":[276.255,473.929,474.905],"minute_ts":1678533754},"temperature":{"tC":51.0, "tF":123.8}},"sys":{"mac":"3C6105799168","restart_required":false,"time":"12:22","unixtime":1678533756,"uptime":234413,"ram_size":234492,"ram_free":156592,"fs_size":458752,"fs_free":98304,"cfg_rev":14,"kvs_rev":0,"schedule_rev":0,"webhook_rev":0,"available_updates":{}},"wifi":{"sta_ip":"192.168.178.202","status":"got ip","ssid":"Skynet","rssi":-31},"ws":{"connected":false}}

A selector between gen1 / gen2 would be great !

**Comment by Telekatz** [comment]
I added the support for the gen2 API to the GEN2 branch for testing.
