### ISSUE TITLE
Support for Shelly Plus PM Mini

### ISSUE THREAD

**Issue by Piet1702** [Telekatz/venus.dbus-shellyPlug#10]
Hi there,

nice project.

Just a quick question.
Is the newly released "Shelly Plus PM Mini" also supported. It's an energy meter without a relay which is just perfect for monitoring pv inverters. 

https://shelly-api-docs.shelly.cloud/gen2/Devices/ShellyPlusPMMini

Kind regards
Piet

**Comment by Telekatz** [comment]
It is not supported yet. But it's not a big effort to add it.

**Comment by Telekatz** [comment]
The “Shelly Plus PM Mini” should now also be recognized. But I couldn't test it with a real device because I don't have such a device.

**Comment by ChristophQ783** [comment]
You did a great Job,
but I use the PM mini als a Counter for an PV Inverter. in the Shelly-App ist shows negative Power. This is shown in the same way in the VRM, but in this Case the PV-inverter "consumes"  the generated power. So i think its a sign-error in the Use case als PV- Inberter.

best regards
Christoph

**Comment by Telekatz** [comment]
Change the wiring and swap the input and output of the PM mini.

**Comment by Telekatz** [comment]
There is now a switch in the settings to reverse the direction of the power meter.
