### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by TimD1981** [Telekatz/venus.dbus-shellyPlug#11]
Hi, 
I'm a fan of your package. It is really great. Good Work!

Maybe you can add a hint to your readme / configuration section. If you have an ip like xxx.xxx.xxx.xx (e.g. 192.168.178.32) you have to fill an zero to get the format .xxx (e.g. .032). I think that is better for all users that are no network nerds ;-)

Some shelly plugs also have an internal temperature sensor. Would it be possible to register the shelly device also as tempearture sensor?

Tim

**Comment by Telekatz** [comment]
I have added the option to display the temperature in the current version.

**Comment by FunkFamily** [comment]
@TimD1981 could you make a package that adds "lcd_rotate=2" to the u-boot config.txt file. I use a raspberry display for my build and having this setting persistent would help alot.
![407050436_3717133245188235_542810770937370494_n](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/63885126/be15d14c-c9d2-43f2-8e4e-092c792d87cd)
