### ISSUE TITLE
No MeterIndexSelector for ShellyPlus2PM - Shelly Plus2PM support ?

### ISSUE THREAD

**Issue by seepv** [Telekatz/venus.dbus-shellyPlug#12]
Thanks for the VenusOS-Addons.

A ShellyPlus1PM works OK, but with an ShellyPlus2PM no "MeterIndex" is showing.
The "switch:0"-Values are OK, but without the "MeterIndex Selector", "switch:1" is not possible to select - do you have an idea ?

Result of
http://192.168.1.1/rpc/Shelly.GetStatus
is:

{"ble":{},"cloud":{"connected":true},"input:0":{"id":0,"state":false},"input:1":{"id":1,"state":false},"mqtt":{"connected":false},"switch:0":{"id":0, "source":"WS_in", "output":false, "apower":0.0, "voltage":227.7, "freq":50.0, "current":0.000, "pf":0.00, "aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1704054510}, "ret_aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1704054510},"temperature":{"tC":35.1, "tF":95.1}},"switch:1":{"id":1, "source":"init", "output":true, "apower":0.0, "voltage":227.8, "freq":50.0, "current":0.127, "pf":0.00, "aenergy":{"total":3310.837,"by_minute":[0.000,0.000,0.000],"minute_ts":1704054510}, "ret_aenergy":{"total":1124.582,"by_minute":[0.000,0.000,0.000],"minute_ts":1704054510},"temperature":{"tC":35.1, "tF":95.1}},"sys":{"mac":"123456789012","restart_required":false,"time":"21:28","unixtime":1704054511,"uptime":16387,"ram_size":244424,"ram_free":129804,"fs_size":458752,"fs_free":131072,"cfg_rev":16,"kvs_rev":2,"schedule_rev":0,"webhook_rev":0,"available_updates":{},"reset_reason":3},"wifi":{"sta_ip":"192.168.1.1","status":"got ip","ssid":"ssid","rssi":-62},"ws":{"connected":false}}

VenusOS v3.13, venus.dbus-shellyPlug (Version 31.12.2023)

**Comment by Telekatz** [comment]
It should be fixed now.

**Comment by seepv** [comment]
That was fast - Yes it's working now - Thanks very much for the Fix.
