### ISSUE TITLE
Change power value in positiv value / add Charger

### ISSUE THREAD

**Issue by Stef293** [Telekatz/venus.dbus-shellyPlug#14]
Hello,

Is it possible to integrate Shelly as a charging controller? I have a shelly 2 p.m. 1 channel for charging the battery and the second for controlling the PV inverter.

The second problem is that the value of channel 2 power (inverter) is negative. it's possible to switch this to a positive value?

Thx.
Stef

**Comment by Telekatz** [comment]
It would be possible to use the Shelly as a charging controller. However, the GUI does not support changing the role to a charge controller. Several changes in the GUI would also be required.

For the other problem I could add a switch to reverse the direction of the power meter.
Can you please give me the output on http://ip-address/rpc/Shelly.GetStatus with both channels active.

**Comment by Stef293** [comment]
Hi attached the shelly output, but for now only the second channel activ. i hope it help. alternated i can add the first channel (charger) tomorrow?

{"ble":{},"cloud":{"connected":true},"input:0":{"id":0,"state":false},"input:1":{"id":1,"state":false},"mqtt":{"connected":true},"switch:0":{"id":0, "source":"HTTP_in", "output":false, "apower":0.0, "voltage":235.0, "freq":50.0, "current":0.000, "pf":0.00, "aenergy":{"total":6350.991,"by_minute":[0.000,0.000,0.000],"minute_ts":1704831756}, "ret_aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1704831756},"temperature":{"tC":49.9, "tF":121.7}},"switch:1":{"id":1, "source":"HTTP_in", "output":true, "apower":-173.3, "voltage":235.0, "freq":50.0, "current":0.742, "pf":1.00, "aenergy":{"total":3093.013,"by_minute":[1882.479,3046.169,3045.233],"minute_ts":1704831756}, "ret_aenergy":{"total":3046.119,"by_minute":[1882.479,3046.169,3045.233],"minute_ts":1704831756},"temperature":{"tC":49.9, "tF":121.7}},"sys":{"mac":"D48AFC426960","restart_required":false,"time":"21:22","unixtime":1704831758,"uptime":123491,"ram_size":244408,"ram_free":132996,"fs_size":458752,"fs_free":131072,"cfg_rev":26,"kvs_rev":0,"schedule_rev":0,"webhook_rev":0,"available_updates":{},"reset_reason":3},"wifi":{"sta_ip":"192.168.0.41","status":"got ip","ssid":"ARRIS-B06A-2G","rssi":-41},"ws":{"connected":false}}

**Comment by Telekatz** [comment]
I added the switch to reverse the direction of the power meter.
