### ISSUE TITLE
Support for Shelly Mini PM Gen 3

### ISSUE THREAD

**Issue by SY-KALINKA** [Telekatz/venus.dbus-shellyPlug#15]
Hi, 
Would it be possible to add support for a generation 3 shelly Mini PM ?
I can see that the mini PM should be included but it does not connect
My shelly sends data to http://192.168.4.16/rpc/Shelly.GetStatus, but not sure how to change it in the script
Thanks

**Comment by Telekatz** [comment]
Please send the output of [http://192.168.4.16/Shelly](http://192.168.4.16/Shelly) and  [http://192.168.4.16/rpc/Shelly.GetStatus](http://192.168.4.16/rpc/Shelly.GetStatus).

**Comment by SY-KALINKA** [comment]
This is output from http://192.168.4.16/shelly


<html><body>
<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filtrer JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">
  |  
-- | --
name | "shelly"
id | "shellypmminig3-ecda3bc32f34"
mac | "ECDA3BC32F34"
slot | 0
model | "S3PM-001PCEU16"
gen | 3
fw_id | "20231219-133933/1.1.0-g34b5d4f"
ver | "1.1.0"
app | "MiniPMG3"
auth_en | false
auth_domain | null

</div>
</body>
</html>

and this is http://192.168.4.16/rpc/shelly.GetStatus

<html><body>
<li class="tabs-menu-item rawdata " role="presentation"><span class="devtools-tab-line"></span></li><li class="tabs-menu-item headers " role="presentation"><span class="devtools-tab-line"></span></li><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filtrer JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">
  |  
-- | --
ble | {}
cloud |  
connected | true
mqtt |  
connected | true
pm1:0 |  
id | 0
voltage | 231.4
current | 0.277
apower | 55.2
freq | 50
aenergy |  
total | 478.86
by_minute |  
0 | 429.089
1 | 643.634
2 | 858.178
minute_ts | 1706883331
ret_aenergy |  
total | 0
by_minute |  
0 | 0
1 | 0
2 | 0
minute_ts | 1706883331
sys |  
mac | "ECDA3BC32F34"
restart_required | false
time | "15:15"
unixtime | 1706883333
uptime | 27466
ram_size | 261500
ram_free | 151976
fs_size | 1048576
fs_free | 708608
cfg_rev | 20
kvs_rev | 6
schedule_rev | 0
webhook_rev | 0
available_updates | {}
reset_reason | 1
wifi |  
sta_ip | "192.168.4.16"
status | "got ip"
ssid | "Kalinka Wifi"
rssi | -62
ws |  
connected | false

</div>
</body>
</html>

**Comment by SY-KALINKA** [comment]
Hi,

Thanks for assistance
I uploaded the screen shots to github

Best regards
Klaus

Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Telekatz** [comment]
Can you try the current version?

**Comment by SY-KALINKA** [comment]
Hi, Thank you so much, now I got it on my device list as an AC meter however it does not appear on the graphic display ThanksKlaus Sendt fra Mail til Windows Fra: TelekatzSendt: 3. februar 2024 15:00Til: Telekatz/venus.dbus-shellyPlugCc: SY-KALINKA; AuthorEmne: Re: [Telekatz/venus.dbus-shellyPlug] Support for Shelly Mini PM Gen 3 (Issue #15) 
Can you try the current version?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Telekatz/venus.dbus-shellyPlug/issues/15#issuecomment-1925329231",
"url": "https://github.com/Telekatz/venus.dbus-shellyPlug/issues/15#issuecomment-1925329231",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SY-KALINKA** [comment]
Hi Again,

Its all good now, showing up on the display mimic

Thanks for the assistance

Best regards
Klaus

Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SY-KALINKA** [comment]
Hi again,

Sorry I was too fast.... It was my inverter that was showing AC Loads.... The shelly device does not show anything on the mimic

Do you have any suggestions?

Best regards
Klaus

Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Telekatz** [comment]
What is the role of your Shelly device?

**Comment by SY-KALINKA** [comment]
Hi,

I changed it from AC Load to Grid Meter and now it shows as AC load ?

Iam just playing now, but want to have a few for my large AC loads.... Like waterheater & heater in the boat.

Have not tested what happens when start the inverter

Best regards
Klaus



Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Telekatz** [comment]
AC loads are only displayed in the device list, not in the graphical display.
