### ISSUE TITLE
Gui incomplete

### ISSUE THREAD

**Issue by realdognose** [Telekatz/venus.dbus-shellyPlug#16]
Hey, 

just found your script and is exactly what I need :) 

However, unfortunately there is an error during installation: 

`svc: warning: unable to chdir to /service/gui: file does not exist`

The GUI of everything looks as described - except the device settings. Beside "role" it is completely empty :( 

![image](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/5311744/e094076e-7901-46b6-826b-de62b81a6285)

Any idea or manual steps to resolve? (I tried to create the folder manually, but it doesn't seem the correct location)

**Comment by realdognose** [comment]
Okay, figured out that  `svc -t /service/gui` should somewhat restart the gui service (which failed?) 

So, I restarted the whole cerbo, now everything is there.

**Comment by tmlarsson** [comment]
Thanks for the comment. I had the same issue and a reboot solved the problem :)

**Comment by Head** [comment]
same issue here, running venus os 3.51
Reboot not helping, however changing the config with dbus-spy over ssh solved my issue to change the IP.
