### ISSUE TITLE
Installation issues /service/gui: file does not exist

### ISSUE THREAD

**Issue by Fiver235** [Telekatz/venus.dbus-shellyPlug#18]
Hi,
when running install.sh on my Cerbo GX I am getting the following error:

root@einstein:/# /data/dbus-shellyPlug/install.sh
patching file /opt/victronenergy/gui/qml/PageAcInSetup.qml
svc: warning: unable to chdir to /service/gui: file does not exist

On the GX console a Shelly device is showing up, but under -> Setup I can't set te Shelly IP adress ; 

![grafik](https://github.com/user-attachments/assets/95ab351d-eff1-46ff-9af5-6b07be77cae7)

Device is showing the following:

![grafik](https://github.com/user-attachments/assets/c847bc60-0b00-4c7e-88f4-1c8742b80ca9)

![grafik](https://github.com/user-attachments/assets/4446bc8f-2a3c-4998-a207-c8e611a1d9f6)

Any idea how to get it running?

Thank you

Rudi

**Comment by Telekatz** [comment]
Reboot Venus OS.
