### ISSUE TITLE
High amount of kWh "counted" at random times

### ISSUE THREAD

**Issue by simsandmann** [Telekatz/venus.dbus-shellyPlug#2]
Hello,

the problem are random energy amounts that are counted over the day. Mostly it happens one time a day.

I run 2 Shelly Plug S as PV inverter and the newest version of the driver is installed. The connection of both Shelly Plugs is weak and they are placed side by side.

![Victron_historical_data](https://user-images.githubusercontent.com/36762514/227042299-2343048b-928a-401c-918e-92e0722fa666.png)

You can see the spike which is added as solar energy. At the same time the consumption rises because the imaginary energy did not leave the network.
You can not see the energy in the Victron remote console, in the graphs of the Shelly Plugs in VRM or in the Shelly Cloud.

Could this be a driver problem?

**Comment by Telekatz** [comment]
Is the height of the spike always the same? 
Can you regularly note the energy value in each "AC Totals" section of the Shelly Plugs? How do the values change after such a spike? 
Are you using a fixed IP address for the Shelly plugs?

**Comment by simsandmann** [comment]
At the beginning the spike was about 10,20 kWh. Since then the spike went higher all the time. It happend about 7 times now and last time the spike was 31,25 kWh.

I will note the values from now on. Unfortunately I did not check the values as I thought they should be visible at the graphs. But they did not.

Yes, fixed IP addresses are used.

As last configuration change two days ago I updated the Shelly Plugs and set the gateway address.

**Comment by Telekatz** [comment]
Is the difference in the energy values of the Shelly plugs about 31kWh? 
I was able to create such a spike by swapping the IP addresses of the Shelly plugs. Maybe it's a problem with the weak connection that after the connection is lost, the Shelly plugs swap IP addresses when they reconnect.

**Comment by simsandmann** [comment]
I did not see the difference last time, but last day it happend again:

From 23:00 - 23:59 it "produced" 3,97 kWh of solar energy. 
One Shelly Plug has 3 kWh and the other one has 3,97 kWh as ac total value.

I would assume that somehow the Shelly ac total is added to the solar energy.

But they should not swap ip addresses when they have fixed ip addresses or?

**Comment by Telekatz** [comment]
I think I found the bug. Can you please try the DEV branch if the bug is fixed with this version.

**Comment by simsandmann** [comment]
I installed the DEV branch and will report next weekend if everything is fine.

**Comment by simsandmann** [comment]
It did not work. There were again 2 counts of solar energy added.

Before I remember just 1 Shelly adding the AC total value. Today each Shelly ac total value was added.

**Comment by Telekatz** [comment]
I added some logging information to the DEV branch. Please test the new version and send the log file after the next occurrence of the bug.

**Comment by simsandmann** [comment]
Shame on me. I messed the installation up by not installing the DEV branch correctly. I reinstalled it 2 days ago and since then everything is fine.

Btw: Is it useful to turn logging off (maybe with the config.ini) to preserve the memory of the Cerbo?

**Comment by Telekatz** [comment]
I will remove the extra logging of the DEV branch before merging it with the main branch.

**Comment by simsandmann** [comment]
I also meant the logging which is already in the main branch. Or does it have any use for a normal user?

**Comment by Telekatz** [comment]
For the normal user there is no need for logging.
