### ISSUE TITLE
Error when installing on Venus 3.10-8

### ISSUE THREAD

**Issue by peterprovoost** [Telekatz/venus.dbus-shellyPlug#5]
root@raspberrypi4:/# /data/dbus-shellyPlug/install.sh
Restore PageAcInSetup.qml
patching file /opt/victronenergy/gui/qml/PageAcInSetup.qml
Hunk 1 FAILED 90/90.
 		onValueChanged: role.possibleValues = getRoleList(value)
 	}
 
+	VBusItem {
+		id: instance
+		bind: Utils.path(root.bindPrefix, "/DeviceInstance")
+	}
+
 	model: VisualItemModel {
 		MbItemOptions {
 			id: role

**Comment by Telekatz** [comment]
Fixed in the branch [Venus_OS_V3.00](https://github.com/Telekatz/venus.dbus-shellyPlug/tree/Venus_OS_V3.00).
