### ISSUE TITLE
install.sh script not fully woring on Venus OSv3.0?

### ISSUE THREAD

**Issue by desertdragonstorm** [Telekatz/venus.dbus-shellyPlug#6]
Hi,
if it´s possible that your script dos not work on the Venus OS v3.0?
on installation process i got a failer: So in the GUI i can not configure the ip etc...

root@raspberrypi2:~# wget https://github.com/telekatz/venus.dbus-shellyPlug/arch                                                                                                                                                             ive/refs/heads/main.zip
--2023-07-18 07:59:15--  https://github.com/telekatz/venus.dbus-shellyPlug/archi                                                                                                                                                             ve/refs/heads/main.zip
unzip main.zip "venus.dbus-shellyPlug-main/*" -d /data
mv /data/venus.dbus-shellyPlug-main /data/dbus-shellyPlug
chmod a+x /data/dbus-shellyPlug/install.sh
/data/dbus-shellyPlug/install.sh
rm main.zipResolving github.com... 140.82.121.4
Connecting to github.com|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Telekatz/venus.dbus-shellyPlug/zip/refs/he                                                                                                                                                             ads/main [following]
--2023-07-18 07:59:16--  https://codeload.github.com/Telekatz/venus.dbus-shellyP                                                                                                                                                             lug/zip/refs/heads/main
Resolving codeload.github.com... 140.82.121.9
Connecting to codeload.github.com|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘main.zip’

main.zip                [  <=>               ] 280.19K  1.29MB/s    in 0.2s

2023-07-18 07:59:17 (1.29 MB/s) - ‘main.zip’ saved [286913]

root@raspberrypi2:~# unzip main.zip "venus.dbus-shellyPlug-main/*" -d /data
Archive:  main.zip
   creating: venus.dbus-shellyPlug-main/
  inflating: venus.dbus-shellyPlug-main/LICENSE
  inflating: venus.dbus-shellyPlug-main/README.md
  inflating: venus.dbus-shellyPlug-main/config.ini
   creating: venus.dbus-shellyPlug-main/img/
  inflating: venus.dbus-shellyPlug-main/img/device.png
  inflating: venus.dbus-shellyPlug-main/img/deviceInfo.png
  inflating: venus.dbus-shellyPlug-main/img/deviceList.png
  inflating: venus.dbus-shellyPlug-main/img/settings.png
  inflating: venus.dbus-shellyPlug-main/install.sh
   creating: venus.dbus-shellyPlug-main/qml/
  inflating: venus.dbus-shellyPlug-main/qml/PageAcInSetup.diff
  inflating: venus.dbus-shellyPlug-main/restart.sh
   creating: venus.dbus-shellyPlug-main/service/
  inflating: venus.dbus-shellyPlug-main/service/run
  inflating: venus.dbus-shellyPlug-main/shellyPlug.py
  inflating: venus.dbus-shellyPlug-main/uninstall.sh
root@raspberrypi2:~# mv /data/venus.dbus-shellyPlug-main /data/dbus-shellyPlug
root@raspberrypi2:~# chmod a+x /data/dbus-shellyPlug/install.sh
root@raspberrypi2:~# /data/dbus-shellyPlug/install.sh
Restore PageAcInSetup.qml
patching file /opt/victronenergy/gui/qml/PageAcInSetup.qml
Hunk 1 FAILED 90/90.
                onValueChanged: role.possibleValues = getRoleList(value)
        }

+       VBusItem {
+               id: instance
+               bind: Utils.path(root.bindPrefix, "/DeviceInstance")
+       }
+
        model: VisualItemModel {
                MbItemOptions {
                        id: role
root@raspberrypi2:~# rm main.zip

**Comment by Telekatz** [comment]
Use the branch [Venus OS V3.00](https://github.com/Telekatz/venus.dbus-shellyPlug/tree/Venus_OS_V3.00).
