### ISSUE TITLE
Shelly EM support? 

### ISSUE THREAD

**Issue by mcfrojd** [Telekatz/venus.dbus-shellyPlug#8]
Any chanse of support for the Single phase Shelly EM?
Maybe i colud support with some data from the EM?

I have tested most of the shelly script out there and yours is by far the best one imo.
Your log handeling and what happens when you disconnect the shellys is superior to the others i have tested.

Since i use mine in a motorhome where you connect and disconnect on a Daily basis, your script is by far the most stable one.

**Comment by Telekatz** [comment]
Looks like the Shelly EM is quite similar than a Shelly Plug.

Please test the branch [shellyEM](https://github.com/Telekatz/venus.dbus-shellyPlug/tree/shellyEM). The first channel of the Shelly EM should be displayed.

**Comment by mcfrojd** [comment]
I tried the Shelly EM branch home on my test setup and it seems to work fine.

I added my Shelly EM as a grid meter and it shows the output fine on L1.

I even tried to add an Shelly Plug S into the mix as an AC Load on L2 but im not sure how it is suppose to look in
remote console or vrm, but i can only see the total draw of them both on L1.
(the PlugS sits after the EM and it's load is included in the EM)

I took some screenshots and put them on https://ibb.co/album/dWHHqn

And a small log snippet on https://pastebin.com/U06xh294

**Comment by mcfrojd** [comment]
Noticed one thing, when i disconnect the EM & PlugS, the latest AC input value remains in VRM.
https://ibb.co/sy2HYYX
But i can see them both as "Not Connected" in the remote consol.
If i reboot the Venus OS Pi the values sets to zero in VRM (https://ibb.co/KhFxfsL)

**Comment by mcfrojd** [comment]
I connected the EM & PlugS again and they both showed up again automaticly.
When i disconnected them again the AC Input value became 0 in VRM (https://ibb.co/xCDNKS0)
Maybe it depends on how close the next VRM update is?
I have it set to 1 min, but maybe i had the VRM page up and the updates was in realtime?

**Comment by desertdragonstorm** [comment]
> Looks like the Shelly EM is quite similar than a Shelly Plug.
> 
> Please test the branch [shellyEM](https://github.com/Telekatz/venus.dbus-shellyPlug/tree/shellyEM). The first channel of the Shelly EM should be displayed.

Hi, i tried it too but on my setting it dose´t work. What do i wrong?
![2023-08-30 21_19_13-Window](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/2410bffd-f277-40e8-b2bf-f18d3e44cdb1)
![2023-08-30 21_19_51-Window](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/566f0f80-fcd6-4306-b8f5-d79f5fa93980)
![2023-08-30 21_20_39-Clipboard](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/cc98b38a-3b99-4a69-a112-7854c1109562)
![2023-08-30 21_21_11-Window](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/76c1e98c-8f99-4925-992d-7071d6b2d827)

**Comment by Telekatz** [comment]
Do you use the first or the second channel of the Shelly EM?

**Comment by desertdragonstorm** [comment]
The first. :) i have found my mistake. Ich had the wrong skript. the plugs skript, not the ..../Telekatz/venus.dbus-shellyPlug/tree/shellyEM skript.

now i only copyed the  new shelly.plug.py and it works.

@Telekatz  can you update the installation guide on tree/shellyEM ? So that the files are downloaded from this path.

thx and good night

**Comment by Telekatz** [comment]
I added a GUI setting to select the measurement channel of the EM. Can someone please test if this is working correctly?

**Comment by desertdragonstorm** [comment]
> I added a GUI setting to select the measurement channel of the EM. Can someone please test if this is working correctly?

Hi Telekatz,
i tried you new Version and it works fine. I can change the messurment input in the gui of venus os.

I noticed that your installation path is the same as the plugS. Can you still change the directory/folder to "dbus-shellyem" So now i can not use both of your scripts
![2023-09-03 07_38_33-Remote Console on LAN](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/3f7421f7-89eb-470a-bc8f-37099980f6e5)
![2023-09-03 07_39_28-Remote Console on LAN](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/4ff91685-c55c-4e77-bcb2-920fc8dde6af)
![2023-09-03 07_40_17-Remote Console on LAN](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/be13642f-8217-42f7-ab58-d596f62cc1a5)
![2023-09-03 07_41_17-Remote Console on LAN](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/e4005d7f-ab5a-4d4d-9218-a137b4d9e5b3)
![2023-09-03 07_42_17-Wohnwagen - VRM Portal](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/127033596/57f2448a-8e71-48ae-b627-b077ed421d0e)


The installation script  works too. Thx alot.

**Comment by Telekatz** [comment]
> I noticed that your installation path is the same as the plugS. Can you still change the directory/folder to "dbus-shellyem" So now i can not use both of your scripts

You only need one script. It works with all types of devices.
