### ISSUE TITLE
AC Load is not shown in GUI and kWh seems to be wrong.

### ISSUE THREAD

**Issue by SvenTej** [Telekatz/venus.dbus-shellyPlug#9]
Hey,
first thanks a lot for this cool project.

My system is built with a 
- MPPT 100/30 Charger
- BMV 712 battery monitor
- Inverter that has no connection to the victron (!)

It is a stand alone system with no connection to grid in a garden.

As I´d linke to know, how much energy is drawn via 240VAC (the inverter) and via DC (I also have some DC loads) I thought I use your script with a Shelly PRO 1EM and configure "has DC System" in the Venus OS.

The readings show up :
![image](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/93467941/8f994451-3629-40a4-a7a9-7049207e2d8a)

The GUI shows:
![image](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/93467941/6f5a098f-a08d-43fa-8600-87e5e0bebd69)

What is a bit strange : 
- after 50 minutes with a load of 1300W the kWh is only. 0,02kWh
- the ACload does not show up in the GUI 
- the complete power drawn is regarded as DC load (the difference between 1300W and 1450W is the efficiency of the inverter.

Is there any chance that the AC load shows up in the GUI?
Where is my fual tin thinking regarding the kWh ?

Can I assist in any way by logs or something else?

Greets from Stuttgart - Germany
Sven

**Comment by SvenTej** [comment]
One addition:
I saw that you divide the value from the shelly json by 60000

energy = shellyData['switch:0']['aenergy']['total']/60000


The shelly reports the energy as Wh, so why the factor 60`?
Where is my fault in thinking ?

Heres the description of the readings:
![image](https://github.com/Telekatz/venus.dbus-shellyPlug/assets/93467941/e33707e8-e764-40ae-b570-138a69844d2f)


It seems as if the reading of "total" is reset each time the Shelly restarts....maybe this is also a useful info.



S.

**Comment by Telekatz** [comment]
The value 60000 was copied from the GEN1 API where total is in watt minutes. I fixed this.

Did you change the role of the meter to PV inverter?

**Comment by SvenTej** [comment]
Hey, thanks for the change,.


Well no, I configured the Shelly as ACload.
If I confire it as PCinverter the statistics are wrong as each Watt that is measured by the Shelly is rated as generated by solarin that moment.
And also the drawn energy from the battery is rated as consumed by DCLoad.

Example:
Battery was charged during the day with 2kWh.
In the night I draw 2kWh from the inverter (shelly measures this output).
If I configure the Shelly as PVInverter, VRM states 4Kwh generated by solar, and 4kWh consumed.

And this is obviously wrong.

My - obvisously wrong - expectation was:
If I configure AC Load, 
- the data is shown in the GUI
- if 1 W is drawn by the AC Load this power is taken from teh DC System because: where should it come from ??

Ay hints for me to solve my issue?

Do you have an inverter in the system?

Sven

PS: maybe we can get into detailled contact to find a solution together ?

**Comment by Telekatz** [comment]
That not how the role acload works in Venus OS. It is not displayed in the GUI and is not taken into account for the energy flow calculation.

What you need is something similar to what I did for the [Hoymiles](https://github.com/Telekatz/venus.dbus-hoymiles) inverter. A dbus service that creates a Multiplus device. With such a device, the energy flow could be displayed in VRM as you want.
